openapi: 3.0.0
info:
  title: 'Swagger Petstore'
  description: "This is a sample Petstore server.  You can find\nout more about Swagger at\n[http://swagger.io](http://swagger.io) or on\n[irc.freenode.net, #swagger](http://swagger.io/irc/)."
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'https://virtserver.swaggerhub.com/swagger/Petstore/1.0.0'
    description: 'SwaggerHUB API Mocking'
paths:
  /pet:
    post:
      tags:
        - pet
      summary: 'Add a new pet to the store.'
      operationId: addPet
      responses:
        405:
          description: 'Invalid input'
      security:
        -
          petstore_auth:
            - 'write:pets'
            - 'read:pets'
tags:
  -
    name: pet
    description: 'Everything about your Pets'
    externalDocs:
      description: 'Find out more'
      url: 'http://swagger.io'
  -
    name: store
    description: 'Access to Petstore orders'
  -
    name: user
    description: 'Operations about user'
    externalDocs:
      description: 'Find out more about store'
      url: 'http://swagger.io'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'
